[package]
name = "tauri-plugin-serialport"
version = "0.0.4"
authors = [ "lzhida" ]
description = "A tauri plugin developed based on Serialport."
edition = "2021"
rust-version = "1.57"
exclude = ["/examples", "/webview-dist", "/webview-src", "node_modules"]

[dependencies]
tauri = { version = "1.0.2" }
serde = "1.0"
thiserror = "1.0"
serialport = {version = "4.2.0"}
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.17"
futures-util = "0.3"
rusqlite = { version = "0.30.0", features = ["bundled"] }
chrono = "0.4"